apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: kubernetes
spec:
  type: LoadBalancer  #указываем тип
  loadBalancerIP: 192.168.99.101
  externalTrafficPolicy: Cluster
  selector:
    app: nginx        #привязываем сервис к нашему контейнеру
  ports:
    - protocol: TCP
      name: ssh
      port: 22
      targetPort: 22
    - protocol: TCP
      name: http
      port: 80        #какой порт хотим открыть
      targetPort: 80  #к какому порту хотим присоединиться
    - protocol: TCP
      name: https
      port: 443        #какой порт хотим открыть
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: service_nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 22
            - containerPort: 80
            - containerPort: 443
